### ISSUE TITLE
Python not recognising files?

### ISSUE THREAD

**Issue by hjb60** [katholt/Kleborate#7]
Hello,
I'm not sure if this is the right place to post or if it's something I'm doing wrong (likely) but I'm getting the following error when trying to run Kleborate:
Kleborate$ python Kleborate.py -p Kleborate -o Detailed_Results.txt *.fa
strain	ST	Yersiniabactin	YbST	Colibactin	CbST	aerobactin	salmochelin	hypermucoidy	wzi	KL 
python: can't open file 'Kleborate/mlstBLAST.py': [Errno 2] No such file or directory
python: can't open file 'Kleborate/mlstBLAST.py': [Errno 2] No such file or directory
python: can't open file 'Kleborate/mlstBLAST.py': [Errno 2] No such file or directory
python: can't open file 'Kleborate/clusterBLAST.py': [Errno 2] No such file or directory
python: can't open file 'Kleborate/mlstBLAST.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "Kleborate.py", line 175, in <module>
    print "\t".join([name,chr_ST,Yb_group,Yb_ST,Cb_group,Cb_ST,vir_hits,wzi_ST,Ktype]),
NameError: name 'vir_hits' is not define

It's very likely I'm doing something obviously wrong but this are isn't my strong point
Thanks

**Comment by katholt** [comment]
You need to point the code to your Kleborate directory using the -p parameter.

Ie your current command should work if you run it from within the directory that contains the Kleborate/ repo as a subdirectory. 

We will get this packaged up properly soon so that you don't need to tell Kleborate where its own path is :)

**Comment by hjb60** [comment]
Hi there,

  Sorry to have to email back - I'm still having similar issues. I'm running the following command in the directory where Kleborate is a sub directory (where it was cloned to via git clone) and having the following issue:
team81/hb10/Torok$ python Kleborate.py -p Kleborate -o Detailed_Results.txt -r on *.fa
python: can't open file 'Kleborate.py': [Errno 2] No such file or directory

Is this an issue with the script or something I'm doing/not doing? :)

Hayley
________________________________

**Comment by kelwyres** [comment]
Hi Hayley, 

Looks like you just need to go down one more directory level so that you run the command from inside the Kleborate directory i.e.

team81/hb10/Torok/Kleborate$ python Kleborate.py -p . -o etc

Or you can stay in the current directory and tell python that the kleborate script is inside the Kleborate subdirectory e.g.

team81/hb10/Torok$ python ./Kleborate/Kleborate.py -p Kleborate -o etc

The default value for -p is 'Kleborate' so if you are already inside the Kleborate directory you need to specify that using the '.' after -p ('.' means the directory where you are)

Kelly
